### ISSUE TITLE
SDRPLay ZIF/LIF parameters in profiles section of config_webrx.py

### ISSUE THREAD

**Issue by jshuggins** [jketterl/openwebrx#105]
Hello,

Apologies if I missed where to do this, but is there a way to expose and set the SDRPlay's LIF/ZIF settings to config_webrx.py?

Thanks.

**Comment by jketterl** [comment]
Hello,

I suppose you are referring to these settings here:

```
     * IF Mode - IF frequency in kHz
       [key=if_mode, default=Zero-IF, type=string, options=(Zero-IF, 450kHz, 1620kHz, 2048kHz)]
```

if so it shouldn't be difficult to include a corresponding mapping in the next version.

**Comment by jshuggins** [comment]
That's great. Thanks!

**Comment by jketterl** [comment]
Completely forgot to post about this, but the latest dev builds have this now, the corresponding config key is `if_mode`. I haven't done any testing myself since I have yet to understand what it's even useful for :grin:

**Comment by jshuggins** [comment]
Thanks. Will give this a test sometime this week.

**Comment by jketterl** [comment]
Any updates on this? Did it work?

**Comment by jshuggins** [comment]
I'm still busy using your system for a bunch of testing Jakob, but will get on this soonest.
