### ISSUE TITLE
Feature Request: Call external scripts on select receiver.

### ISSUE THREAD

**Issue by KeyOz** [jketterl/openwebrx#110]
In order to be able to use a receiver with several antennas, it would be good to have the option in the profiles in the Config to set the call of an external script or program. This should be called up when you select it. So you can easily and independently control your own hardware to switch antennas and filters.

**Comment by jketterl** [comment]
I'm sorry, but that's a no, at least not in the form of externally called commands. This is very arbitrary and uncontrollable.
