### ISSUE TITLE
where is js8py

### ISSUE THREAD

**Issue by d9394** [jketterl/openwebrx#113]
in /owrx/js8.py line 4 & 5:
from js8py import Js8
from js8py.frames import Js8FrameHeartbeat, Js8FrameCompound
but I can't find js8py folder or js8py.py file

**Comment by jketterl** [comment]
That's because it's a separate library. https://github.com/jketterl/js8py

It's automatically installed via package managers, is contained in the docker images, and the manual installation procedures have been updated to include it.
