### ISSUE TITLE
Digiham C compiling

### ISSUE THREAD

**Issue by IZ3GAC** [jketterl/openwebrx#116]
Hi All, I am trying to manual install openwebrx but compling digiham optional package, there was an issue. cmake.. command, in fact, finished his work with this info: "cmake error at cmake/FindLibMbe ... (MESSAGE) Could not find mbe".
Can anyone helm me solving? Thanks in advance.

**Comment by jketterl** [comment]
There's a paragraph before digiham which takes care of mbelib, which is the part that's missing. Have you run through that?

**Comment by IZ3GAC** [comment]
Many thanks, excuse my trifle...I downloaded the right folder but I missed compiling. 
Now, there is an other big issue.
The openwebrx starts correctly but: 1. there isn't the windows menu for selecting radio bands; 2. there isn't audio ... the bar graph in completely down!

**Comment by jketterl** [comment]
I don't really understand the last part. I don't know what  you've done in the meantime. I don't know what's going wrong. Please check the logs!

**Comment by IZ3GAC** [comment]
In the window - on the left down webpage corner - i see: "Audio underrun [0.0s]" "Audio output [0.0 Ksps]" "Audio stream [0 Kbps]" ... also squelch doesn't work. .... I try to find log and view issues. Could you give me some advices for selecting radio bands? I can choose only 70 cm and 2m by selecting "rtl-sdr usb stick 70cm relais" and "rtl-sdr usb stick 2m komplett"!

**Comment by jketterl** [comment]
Yeah I'll definitely need a log to be able to tell anything.

Look, this is a place for issues, not for conversation or recommendations. Please leave it at that. Feel free to join the mailing list for smalltalk.

**Comment by jketterl** [comment]
So how about that logfile? any updates? I'll close this for inactivity otherwise.
