### ISSUE TITLE
Custom demodulator maximum bandwidth? + FM issues

### ISSUE THREAD

**Issue by Aang23** [jketterl/openwebrx#132]
I recently installed OpenWebRx to share what my VHF (satellite band, 137Mhz) receives. Working pretty well and thanks to Soapy support I didn't have to change anything in my setup.

Working pretty well but a few things :
- FM demodulation (may have missed something in the documentation) can't be set to high enough bandwidth that's required for APT downlinks. About this I went ahead I modified the defaults in the code, which worked to some extent but causes several other issues (Cannot be resized to to a lower bandwidth from the web interface).
- Again, once I do set a larger maximum bandwidth in the code, FM demodulation doesn't work reliably anymore, I will record a sample next time.
- More of a feature request, but it would be pretty convenient if I/Q audio support (as KiwiSDR has) was an option as some point, since forwarding raw I/Q into a local demodulator would allow for much more flexibility.

Thanks for keeping this software updated!

**Comment by jketterl** [comment]
There is no point in setting a higher FM bandwidth; It is constrained by the audio bandwidth between the client and the server. That is set to somewhere between 8 and 12kHz, depending on the audio hardware. So, the maximum audio frequencies is limited to 6 kHz at best.

The FM demodulator is intended for use with narrowband FM only.
