### ISSUE TITLE
Registration site

### ISSUE THREAD

**Issue by Challado** [jketterl/openwebrx#138]
Dear friends.
While sdr.ru stops working / registrating new members to put the radio listen to anyone, how are the substitute / workaround to put my new openwebrx device disponible to anything? Exists a substitute or another way to do that?

**Comment by jketterl** [comment]
There's a separate project that I have started. Please checkout https://www.receiverbook.de/

It's just a few weeks old, so I guess it will take some time until it makes its rounds...

**Comment by Challado** [comment]
Ah, ok.
Doesn't have anything to put on config_webrx.py to register / unregister to
see the SDR status online / offline for now?

Em ter., 23 de jun. de 2020 às 14:45, Jakob Ketterl <
notifications@github.com> escreveu:

**Comment by jketterl** [comment]
Not necessarily, but that depends on the exact scenario. You may need to add a `receiver_key`. But the site should guide you through the process.

**Comment by Challado** [comment]
Ok. When I will put the SDR online I'll back to site. The registration process is OK. I'll go when I have a valid ip address to do so.
