### ISSUE TITLE
Calculate the correct samp_rate

### ISSUE THREAD

**Issue by Challado** [jketterl/openwebrx#139]
Newbie question:
how to calculate the correct samp_rate for each frequency? Now I use the 500000 for my FOXWAY SRP1 Clone to all bands, but I see on the default config_webrx.py a 30m band configuration with other value. Exists a correct formula to do that configuration or it's ok to use 500000 on all profiles?

**Comment by jketterl** [comment]
There is formula to calculate the "correct" sample rate, you do however need to make sure that the sample rate you intend to use is available on your specific hardware. The most reliable tool to determine the available rates has been `SoapySDRUtil --probe`.

The sample rate will influence the "width" of the spectrum you will see. A sample rate of 500k will give you 500kHz of usable spectrum, 1000k will give you 1MHz of usable spectrum, and so on.
