### ISSUE TITLE
WFM bands

### ISSUE THREAD

**Issue by Challado** [jketterl/openwebrx#140]
How to configure openwebrx to listen WFM bands? I only see a big big big carrier wave on screen but won't hear nothing. If I put in AM mode can hear something...

**Comment by jketterl** [comment]
There is no Wideband FM (WFM) demodulator in OpenWebRX, so you can't demodulate WFM. The audio bandwidth of the client in insufficient to transmit WFM, so there's currently no point in stuffing one in there either.

P.S. For general requests please use the mailing list. This area is for issues in the software.
