### ISSUE TITLE
Waterfall_min and max for each receiver please

### ISSUE THREAD

**Issue by zanco** [jketterl/openwebrx#157]
I would like to have a waterfall_min and waterfall_max setting for each receiver hardware device, and if possible for each "frequency range" for each receiver.

The values for an rtl_sdr and an airspy (mini) are way out of each others reach so it's difficult to fit them in one waterfall setting.

Also, the instructions pointed to in the config_webrx.py (for setting the waterfall values by using the developers tools) as in the wiki https://github.com/simonyiszk/openwebrx/wiki appear not to work. it gives an error:

DevTools failed to load SourceMap: Could not load content for http://websdr.pe2bz.nl:8082/compiled/jquery.nanoscroller.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
so, waterfall_measure_minmax = true; gives no output.

**Comment by jketterl** [comment]
This is already possible, please see the documentation: https://github.com/jketterl/openwebrx/wiki/SDR-device-and-profile-configuration#waterfall_min_level-and-waterfall_max_level

The instructions in the config are outdated. I thought I had eliminated all references to the old wiki, but I guess I missed that one. The measurement process has been removed during a change in architecture, there is no replacement yet. You can try to get some rough estimates with the level meter, or read the current configuration from the variables `waterfall_min_level` / `waterfall_max_level` on the developer console.
