### ISSUE TITLE
Image not writble

### ISSUE THREAD

**Issue by 112bzo** [jketterl/openwebrx#167]
How can i writh to my sd card.

Ik will chance the config but my Pi say "not writble"

How to

**Comment by jketterl** [comment]
Please use the issue templates. This is not even an issue, and I will close this. Requests of this nature should go to the mailing list and the issue templates are supposed to guide you there.

There's no restrictions on the writeablity of the SD card or the images. The config is owned by root and you do not have the required permissions to write to that file as a regular user. Please take a minute and read into the file system permission system of linux.
