### ISSUE TITLE
Setting up Scheduler

### ISSUE THREAD

**Issue by G7NFK** [jketterl/openwebrx#169]
Good morning
I'm trying to setup Scheduler but when i copy and paste your example or write my own into configrx_webrx.py then save and reboot i get Error 503 Backend fetch failed, when I remove the scheduler all is well again.

I'm using SDRplay RSP1A .
All the back ground decoding works very well just having a problem with the Scheduler  

Regards Jon G7NFK

**Comment by jketterl** [comment]
Hello John,

please send your request to the mailing list. This is most likely a syntax problem and therefore not an OpenWebRX issue.

Also, when opening issues, please use the issue templates.

73s
Jakob DD5JFK
