### ISSUE TITLE
Problem With SDRPlay API V 3.07.02

### ISSUE THREAD

**Issue by Challado** [jketterl/openwebrx#174]
When I upgrade to version 0.20.0-dev, and API 3.07.02, the follow error has ocurred
Aug 31 10:22:47 sdr openwebrx[12525]: 2020-08-31 10:22:47,466 - owrx.__main__ - INFO - OpenWebRX version v0.20.0-dev starting up...
Aug 31 10:22:47 sdr openwebrx[12525]: 2020-08-31 10:22:47,537 - owrx.sdr - INFO - SDR sources loaded. Available SDRs: SDRPLAY RSP1A
Aug 31 10:23:00 sdr openwebrx[12525]: 2020-08-31 10:23:00,227 - owrx.connection - DEBUG - client connection intitialized
Aug 31 10:23:00 sdr openwebrx[12525]: 2020-08-31 10:23:00,239 - owrx.source - DEBUG - activating profile 0
Aug 31 10:23:01 sdr openwebrx[12525]: 2020-08-31 10:23:01,154 - owrx.source - INFO - Started sdr source: soapy_connector -P 0 -a "Antenna A" -g IFGR=20,RFGR=8 -s 500000 -f 240000 -p 56419 -c 38525 -d driver=sdrplay -t if_mode=0
Aug 31 10:23:01 sdr openwebrx[12525]: setting up control socket...
Aug 31 10:23:01 sdr openwebrx[12525]: control socket started on 56419
Aug 31 10:23:01 sdr openwebrx[12525]: socket setup complete, waiting for connections
Aug 31 10:23:01 sdr soapy_connector: [12680]: sdrplay_api_Open
Aug 31 10:23:01 sdr openwebrx[12525]: [INFO] devIdx: 0
Aug 31 10:23:01 sdr openwebrx[12525]: [INFO] hwVer: 255
Aug 31 10:23:01 sdr sdrplay_apiService: [12685]: sdrplay_apiService_device: mCmdHandlerThread: Entry
Aug 31 10:23:01 sdr sdrplay_apiService: [12686]: sdrplay_apiService_rsp: streamThread: Entry
Aug 31 10:23:01 sdr soapy_connector: [12687]: sdrplay_api_device: strmHandlerThread: Entry
Aug 31 10:23:01 sdr sdrplay_apiService: [12685]: sdrplay_apiService_rsp_log_enable 3
Aug 31 10:23:01 sdr soapy_connector: [12689]: sdrplay_api_device: heartBeatThread: Entry
Aug 31 10:23:01 sdr soapy_connector: [12688]: sdrplay_api_device: eventHandlerThread: Entry
Aug 31 10:23:01 sdr sdrplay_apiService: [12408]: sdrplay_apiService_log_enable: 0
Aug 31 10:23:01 sdr sdrplay_apiService: [12685]: sdrplay_apiService_rsp_log_enable 0
Aug 31 10:23:01 sdr openwebrx[12525]: Setting gain element IFGR: 20.000000 dB
Aug 31 10:23:01 sdr openwebrx[12525]: Setting gain element RFGR: 8.000000 dB
Aug 31 10:23:01 sdr openwebrx[12525]: [INFO] Using format CS16.
Aug 31 10:23:01 sdr sdrplay_apiService: [12408]: sdrplay_apiService_log_enable: 0
Aug 31 10:23:01 sdr sdrplay_apiService: [12685]: sdrplay_apiService_rsp_log_enable 0
**Aug 31 10:23:01 sdr openwebrx[12525]: #033[1m#033[31m[ERROR] error in activateStream() - Init() failed: sdrplay_api_Fail#033[0m**
Aug 31 10:23:01 sdr openwebrx[12525]: client connection establised
Aug 31 10:23:01 sdr openwebrx[12525]: 2020-08-31 10:23:01,258 - owrx.source.connector - DEBUG - opening control socket...
Aug 31 10:23:01 sdr openwebrx[12525]: control connection established
Aug 31 10:23:01 sdr openwebrx[12525]: 2020-08-31 10:23:01,259 - owrx.dsp - DEBUG - received STATE_RUNNING, attempting DspSource restart
Aug 31 10:23:01 sdr openwebrx[12525]: 2020-08-31 10:23:01,430 - owrx.fft - DEBUG - Spectrum thread initialized successfully.
Aug 31 10:23:01 sdr openwebrx[12525]: 2020-08-31 10:23:01,430 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 56419 | csdr fft_cc 8192 3267.97385620915 | csdr logaveragepower_cf -70 8192 17 | csdr fft_exchange_sides_ff 8192 | csdr compress_fft_adpcm_f_u8 8192
Aug 31 10:23:01 sdr openwebrx[12525]: client connection establised
Aug 31 10:23:01 sdr openwebrx[12525]: Connection to 127.0.0.1 56419 port [tcp/*] succeeded!
Aug 31 10:23:02 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:02 sdr openwebrx[12525]: 2020-08-31 10:23:02,485 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 56419 | csdr shift_addfast_cc --fifo /tmp/openwebrx/openwebrx_pipe_shift_pipe_3042092464 | csdr fir_decimate_cc 41 0.0036585365853658534 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx/openwebrx_pipe_bpf_pipe_3040774544 0.02624 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx/openwebrx_pipe_squelch_pipe_3040774448 --outfifo /tmp/openwebrx/openwebrx_pipe_smeter_pipe_3040775120 5 2 | csdr amdemod_cf | csdr fastdcblock_ff | csdr fractional_decimator_ff 1.016260162601626 | csdr agc_ff --profile slow --initial 200 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
Aug 31 10:23:02 sdr openwebrx[12525]: 2020-08-31 10:23:02,495 - owrx.dsp - DEBUG - adding new output of type audio
Aug 31 10:23:02 sdr openwebrx[12525]: fir_decimate_cc: taps_length = 1093
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fir_decimate_cc: taps_length = 1093
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fir_decimate_cc: padded_taps_length = 1096
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fir_decimate_cc: taps = 145b168
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fir_decimate_cc: NEON aligned taps = 145b180
Aug 31 10:23:02 sdr openwebrx[12525]: csdr squelch_and_smeter_cc: fifo control mode on
Aug 31 10:23:02 sdr openwebrx[12525]: client connection establised
Aug 31 10:23:02 sdr openwebrx[12525]: Connection to 127.0.0.1 56419 port [tcp/*] succeeded!
Aug 31 10:23:02 sdr openwebrx[12525]: 2020-08-31 10:23:02,500 - owrx.dsp - DEBUG - adding new output of type smeter
Aug 31 10:23:02 sdr openwebrx[12525]: csdr bandpass_fir_fft_cc: fifo control mode on
Aug 31 10:23:02 sdr openwebrx[12525]: csdr shift_addfast_cc: fifo control mode on
Aug 31 10:23:02 sdr openwebrx[12525]: AGC PARAMS:
Aug 31 10:23:02 sdr openwebrx[12525]:   hang_time = 600
Aug 31 10:23:02 sdr openwebrx[12525]:   reference = 0.800000
Aug 31 10:23:02 sdr openwebrx[12525]:   attack_rate = 0.010000
Aug 31 10:23:02 sdr openwebrx[12525]:   decay_rate = 0.000100
Aug 31 10:23:02 sdr openwebrx[12525]:   max_gain = 65536.000000
Aug 31 10:23:02 sdr openwebrx[12525]:   initial_gain = 200.000000
Aug 31 10:23:02 sdr openwebrx[12525]:   attack_wait_time = 0
Aug 31 10:23:02 sdr openwebrx[12525]:   gain_filter_alpha = 1.500000
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fractional_decimator_ff: use_prefilter = 0, num_poly_points = 12, transition_bw = 0.03, window = HAMMING
Aug 31 10:23:02 sdr openwebrx[12525]: csdr fractional_decimator_ff: not using taps
Aug 31 10:23:02 sdr openwebrx[12525]: csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 153) + (input_size = 360) - 1
Aug 31 10:23:02 sdr openwebrx[12525]: (overlap_length = 152) = taps_length - 1
Aug 31 10:23:02 sdr openwebrx[12525]: csdr shift_addfast_cc: csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.328, high_cut = 0.328
Aug 31 10:23:02 sdr openwebrx[12525]: reinitialized to -0
Aug 31 10:23:02 sdr openwebrx[12525]: csdr squelch_and_smeter_cc: initial squelch level is 1e-15
Aug 31 10:23:03 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:04 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:05 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:06 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:07 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:08 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:09 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:10 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:11 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:12 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:13 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:14 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:15 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:16 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:17 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:18 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:19 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!
Aug 31 10:23:20 sdr openwebrx[12525]: WARNING: SoapySDRDevice_readStream timeout!

**Comment by jketterl** [comment]
Please use the issue template. Also, that's a Problem with SDRPlay or SoapySDRPlay, not OpenWebRX.
