### ISSUE TITLE
Option to call user script on profile change

### ISSUE THREAD

**Issue by jwt27** [jketterl/openwebrx#179]
**Feature description**
Recently I bought an upconverter so I no longer need to use direct sampling on my RTL-SDR.  I replaced the passthrough switch on it with a relay which I can control through the GPIO pins on a remote Raspberry Pi.

Now it would be nice if there was some way for OpenWebRX to toggle the relay automatically, depending on the selected profile.  I think the easiest and most general-purpose way to do this, is by making owrx call a shell script whenever the profile setting changes.  This script can then ssh into the Pi and toggle the GPIO pin.  This could also be used for any other purpose, eg. controlling an antenna switch box, or simply logging profile changes.

The way I see it, this feature could take one of two forms:
Either simply have a profile-level setting, eg `"exec"` that is executed upon activating the profile.
Or, have a device-level setting, for example `"profile_change_script"`, that is called with the profile name and/or center frequency as parameters.  Then you only need one script that can potentially perform multiple actions.

**Target audience**
This could be useful to anyone with a remote-activated upconverter or antenna switch, and has possibly many other uses.

**Comment by jketterl** [comment]
Sorry, but that's nothing I'll be including. Calling external scripts is a very powerful means, it's completely arbitrary and it will lead to a lot of cases of either incorrect use or misuse.

This has been denied before: #110
