### ISSUE TITLE
Improvement UI: show band on top of the page if the shown area is within a band like kiwisdr

### ISSUE THREAD

**Issue by hubertmeier** [jketterl/openwebrx#182]
Hi Jakob,

thank you for your work at openwebrx. In the file **bands.json**, the upper and lower end of the band are coded:

    "name": "160m",
    "lower_bound": 1810000,
    "upper_bound": 2000000,

It would be nice if the band-name would be displayed if the shown area is within the band-edges, like the kiwisdr. If thats not possible or too much work, then it is perhaps possible to display the two edges of a band as markers (with other color? And an arrow which directs to the other marker?)
![kiwi-band](https://user-images.githubusercontent.com/20687189/95477334-85355800-0988-11eb-839a-d78ca4bd84ea.jpg)

**Comment by jketterl** [comment]
Use the issue template!
