### ISSUE TITLE
PACKET window not showing UTC time of received frame

### ISSUE THREAD

**Issue by miodzicho** [jketterl/openwebrx#186]
**Describe the bug**
In PACKET window not showing UTC time of received APRS transmission

**To Reproduce**
Tune to 2m, click on PACKET, wait for received transmissions

**Expected behavior**
In PACKET window should be visible UTC time of received APRS transmission

**Installation method**
Raspberry Pi SD card image

**Versions**
OpenWebRX version v0.20.0

**Log messages**
Oct 22 14:33:36 openwebrx systemd[1]: Started OpenWebRX WebSDR receiver.
Oct 22 14:33:45 openwebrx openwebrx[865]: 2020-10-22 14:33:45,756 - owrx.__main__ - INFO - OpenWebRX version v0.20.0 starting up...
Oct 22 14:33:58 openwebrx openwebrx[865]: 2020-10-22 14:33:58,131 - owrx.sdr - INFO - SDR sources loaded. Available SDRs: RTL-SDR USB Stick
Oct 22 14:33:58 openwebrx openwebrx[865]: 2020-10-22 14:33:58,138 - owrx.source - DEBUG - activating profile 70cm
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,696 - owrx.connection - DEBUG - client connection intitialized
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,713 - owrx.source - INFO - Started sdr source: rtl_connector -P 0 -g 29 -s 2400000 -f 438800000 -p 51889 -c 51069
Oct 22 14:34:14 openwebrx openwebrx[865]: setting up control socket...
Oct 22 14:34:14 openwebrx openwebrx[865]: control socket started on 51889
Oct 22 14:34:14 openwebrx openwebrx[865]: socket setup complete, waiting for connections
Oct 22 14:34:14 openwebrx openwebrx[865]: Found 1 device(s):
Oct 22 14:34:14 openwebrx openwebrx[865]:   0:  Realtek, RTL2838UHIDIR, SN: 00000001
Oct 22 14:34:14 openwebrx openwebrx[865]: Using device 0: Generic RTL2832U OEM
Oct 22 14:34:14 openwebrx openwebrx[865]: client connection established
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,817 - owrx.source.connector - DEBUG - opening control socket...
Oct 22 14:34:14 openwebrx openwebrx[865]: control connection established
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,822 - owrx.dsp - DEBUG - received STATE_RUNNING, attempting DspSource restart
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,832 - owrx.bands - WARNING - Frequency for wspr on 4m is not within band limits: 70091000
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,842 - owrx.fft - DEBUG - Spectrum thread initialized successfully.
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,842 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 51889 | csdr fft_cc 4096 2867.383512544803 | csdr logaveragepower_cf -70 40
Oct 22 14:34:14 openwebrx openwebrx[865]: 2020-10-22 14:34:14,852 - owrx.dsp - DEBUG - received STATE_RUNNING, attempting DspSource restart
Oct 22 14:34:14 openwebrx openwebrx[865]: Connection to 127.0.0.1 51889 port [tcp/*] succeeded!
Oct 22 14:34:14 openwebrx openwebrx[865]: client connection established
Oct 22 14:34:14 openwebrx openwebrx[865]: Detached kernel driver
Oct 22 14:34:15 openwebrx openwebrx[865]: Found Rafael Micro R820T tuner
Oct 22 14:34:15 openwebrx openwebrx[865]: [R82XX] PLL not locked!
Oct 22 14:34:15 openwebrx openwebrx[865]: Allocating 2 zero-copy buffers
Oct 22 14:34:15 openwebrx openwebrx[865]: closing client socket
Oct 22 14:34:16 openwebrx openwebrx[865]: 2020-10-22 14:34:16,447 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 51889 | csdr shift_addfast_cc --fifo /tmp/openwebrx/openwebrx_pipe_shift_pi
Oct 22 14:34:16 openwebrx openwebrx[865]: 2020-10-22 14:34:16,456 - owrx.dsp - DEBUG - adding new output of type audio
Oct 22 14:34:16 openwebrx openwebrx[865]: fir_decimate_cc: taps_length = 5333
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr fir_decimate_cc: taps_length = 5333
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr fir_decimate_cc: padded_taps_length = 5336
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr fir_decimate_cc: taps = 1541168
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr fir_decimate_cc: NEON aligned taps = 1541180
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr shift_addfast_cc: fifo control mode on
Oct 22 14:34:16 openwebrx openwebrx[865]: 2020-10-22 14:34:16,461 - owrx.dsp - DEBUG - adding new output of type smeter
Oct 22 14:34:16 openwebrx openwebrx[865]: Connection to 127.0.0.1 51889 port [tcp/*] succeeded!
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr squelch_and_smeter_cc: fifo control mode on
Oct 22 14:34:16 openwebrx openwebrx[865]: client connection established
Oct 22 14:34:16 openwebrx openwebrx[865]: AGC PARAMS:
Oct 22 14:34:16 openwebrx openwebrx[865]:   hang_time = 600
Oct 22 14:34:16 openwebrx openwebrx[865]:   reference = 0.800000
Oct 22 14:34:16 openwebrx openwebrx[865]:   attack_rate = 0.010000
Oct 22 14:34:16 openwebrx openwebrx[865]:   decay_rate = 0.000100
Oct 22 14:34:16 openwebrx openwebrx[865]:   max_gain = 3.000000
Oct 22 14:34:16 openwebrx openwebrx[865]:   initial_gain = 1.000000
Oct 22 14:34:16 openwebrx openwebrx[865]:   attack_wait_time = 0
Oct 22 14:34:16 openwebrx openwebrx[865]:   gain_filter_alpha = 1.500000
Oct 22 14:34:16 openwebrx openwebrx[865]: csdr bandpass_fir_fft_cc: fifo control mode on

**Comment by jketterl** [comment]
The APRS protocol does not mandate a timestamp on the transmitted packages. As such, you will only see a time in the "UTC" column when the received packet contained one.
