### ISSUE TITLE
Contnue: Version 0.20.0 does not display avatar

### ISSUE THREAD

**Issue by Abdula-2015** [jketterl/openwebrx#190]
I've been watching you for a long time, you vile and aggressive fascist.
People offer you useful improvements to OpenWebRX. But instead of listening to valuable suggestions, you snarl and are rude to people.
 I'm currently using WebSDR, and I wanted to switch to OpenWebRx. But I can see that you're a nasty bastard, so I won't do it. 
**ou are a bastard, and I will find you in Germany and punch you to correct your boorish behavior!**
And you don't do OpenWebRx anymore, it's better to let other polite people do it!

**Comment by jketterl** [comment]
reported to github for agression and threats. I am not going to discuss any further.
