### ISSUE TITLE
Unsupported soundcard mode causes application to hang

### ISSUE THREAD

**Issue by alexander-pick** [jketterl/openwebrx#192]
An soundcard with a not supported mode will cause an unhandled exception in the receiver.js (AudioEngine.js):

```
receiver.js:3946 Uncaught ReferenceError: targetRate is not defined
    at AudioEngine.setupResampling (receiver.js:3946)
    at new AudioEngine (receiver.js:3763)
    at openwebrx_init (receiver.js:1422)
    at onload ((index):32)
``` 

The var targetRate istused in the divlog error messages but it seems it is undefined. This will cause the whole application to hang and the waterfall won't load. You will be stuck with the background and the header. 

The error is triggered in the following code upon divlog():

```
AudioEngine.prototype.setupResampling = function() { //both at the server and the client
    var audio_params = this.findRate(8000, 12000);
    if (!audio_params) {
        this.resamplingFactor = 0;
        this.outputRate = 0;
        divlog('Your audio card sampling rate (' + targetRate + ') is not supported.<br />Please change your operating system default settings in order to fix this.', 1);
    } else {
        this.resamplingFactor = audio_params.resamplingFactor;
        this.outputRate = audio_params.outputRate;
    }

    var hd_audio_params = this.findRate(36000, 48000);
    if (!hd_audio_params) {
        this.hdResamplingFactor = 0;
        this.hdOutputRate = 0;
        divlog('Your audio card sampling rate (' + targetRate + ') is not supported for HD audio<br />Please change your operating system default settings in order to fix this.', 1);
    } else {
        this.hdResamplingFactor = hd_audio_params.resamplingFactor;
        this.hdOutputRate = hd_audio_params.outputRate;
    }
};
```

I encountered the issue by accidently setting my headset to handfree mode which seems to run in a unsupported mode and could only see the error by digging in the developer tools console for it.

**Comment by jketterl** [comment]
Interesting. I have never had the opportunity to do much testing in this scenario since I am unable to reproduce it...

**Comment by jketterl** [comment]
Alright, this was the result of some refactoring some while ago. The commit above should fix the JavaScript error, it can however not compensate for the unsupported sound card sample rate. You will see an error message in log window in the browser, but you still won't get any audio because the server is not able to provide the audio in the corresponding sample rate.

Just out of curiosity, what sample rate are you running when the error appears?
