### ISSUE TITLE
WikiMedia map tiles throwing errors

### ISSUE THREAD

**Issue by ofadam** [jketterl/openwebrx#195]
On the console output for the map in openwebrx, it looks like the fallback maps from OSM are causing 403 forbidden errors now – I wonder what changed?

**Comment by jketterl** [comment]
Use the issue template! If nobody is willing to support my work by at least following the correct workflow, I will start closing tickets without further comment!!!

It's being blocked by wikimedia, nothing I can do about that. This has been discussed on the support group, too: https://groups.io/g/openwebrx/topic/no_background_map/77623409

Unfortunately, so far nobody is willing or able to tackle this, so the OSM fallback will probably be removed in the next version.
