### ISSUE TITLE
Customization of APRS IGate Beacon Details

### ISSUE THREAD

**Issue by ewsandor** [jketterl/openwebrx#198]
**Feature description**
I would like to suggest the option to customize details about their APRS IGate beacon reported to the APRS network.  

I have added this support on my local instance.  If this is a feature people are interested in, I can formalize my change and raise a pull request.  

I started by wanting to include the URL of my receiver in the comment, but also added support to specify symbol, antenna details, and a contact frequency.  I accomplish this by updating to the Dire Wolf config generated in kiss.py to specify additional PBEACON parameters.

**Target audience**
This feature may be interesting to users who have enabled APRS reporting on their receiver and would like to customize their beacon.

**Current Raw Packet**
2020-12-12 11:08:06 MST: KC9ZQW>APDW14,TCPIP*,qAC,T2DALLAS:!4008.58NR10509.06W&OpenWebRX APRS gateway
**Example Customized Raw Packets**
2020-12-12 10:55:53 MST: KC9ZQW>APDW14,TCPIP*,qAC,T2PR:!4008.58NR10509.06W&PHG0100146.955MHz T074 -060 OpenWebRX APRS gateway - sdr.sandorlabs.us

![Screenshot from 2020-12-12 11-34-08](https://user-images.githubusercontent.com/1273949/101992503-0fdc5100-3c71-11eb-884d-948d28a81ce9.png)

**Comment by jketterl** [comment]
Should be reolved since the merge of #202, or is there anything missing?
