### ISSUE TITLE
<dev> FT8 and other decoding doesn't work

### ISSUE THREAD

**Issue by sq4bja** [jketterl/openwebrx#212]
Hi,
Decoding of digital broadcasts does not work after the last dev version update. Both in the background and in the user interface.
Openwebrx downloaded as a package from the Debian repository from the dev branch.

From logs:
```
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,000 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,001 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,001 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,001 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,001 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file
Jan 16 11:46:15 websdr openwebrx[882]: 2021-01-16 11:46:15,002 - owrx.audio - WA
RNING - decoding queue overflow; dropping one file

```
Tom SQ4BJA

**Comment by jketterl** [comment]
First of all, I'd really appreciate if you could use the issue template.

Second, the log messages about the queue being full are probably just a secondary error, the real error should be further up in the log.

If I had to guess, I'd say you're probably missing some new config settings (`wsprnet_enabled`) that were introduced (happened to myself last night). I will make them optional.

**Comment by sq4bja** [comment]
Hello, sorry for the wrong issue format.
You were right, the new configuration options have disabled ft8 decoding. After adding the missing options, everything started to work.

**Comment by jketterl** [comment]
You can update the package from the repo now, too, I added a check and it should default wsprnet reporting to off if the config keys are missing.

Resolved?

**Comment by sq4bja** [comment]
Yes, thank You!
