### ISSUE TITLE
The default APRS comment cannot be changed to your own.

### ISSUE THREAD

**Issue by s-s-s** [jketterl/openwebrx#216]
The default APRS comment does not change.

**Installation method**
Debian,  manually

**Versions**
OpenWebRX 0.20.3

**Comment by jketterl** [comment]
I'd really appreciate if you didn't slice the templates at your own will. Right now, I don't know if this is supposed to be a bug report or a feature request.

If this is a bug report: OpenWebRX 0.20 does not contain the functionality to change APRS details.

If this is a feature request: It's a duplicate. This has already been implemented in #198 

Closing.
