### ISSUE TITLE
Support for frequency-inverting downconverter

### ISSUE THREAD

**Issue by MustBeArt** [jketterl/openwebrx#218]
I'm running a 10 GHz receiver using an off-shelf LNB. These all use low-side injection of the local oscillator, so they present an inverted IF spectrum to the SDR. It'd be nice if the spectrum display and its frequency scale could be flipped to display the correct actual frequencies in this case.

**Comment by jketterl** [comment]
I would really appreciate if you'd use the issue template.

Devices that run on connector infrastructure can use the `iqswap` option, see documentation: https://github.com/jketterl/openwebrx/wiki/SDR-device-and-profile-configuration#iqswap
