### ISSUE TITLE
SoapyRemote Timeout

### ISSUE THREAD

**Issue by n1zzo** [jketterl/openwebrx#219]
**Describe the bug**
When using OpenWebRx with SoapyRemote, after some time the stream stops, no waterfall is visible and logs show:
```
openwebrx    | WARNING: SoapySDR::Device::readStream timeout!
openwebrx    | WARNING: SoapySDR::Device::readStream timeout!
openwebrx    | WARNING: SoapySDR::Device::readStream timeout!
```
Restarting SoapyRemote does not solve the issue, restarting openwebrx does.

**To Reproduce**
Configure OpenWebRx with SoapyRemote and leave a protocol decoder to be active while no user is active, then wait.

**Expected behavior**
The stream from the SDR should not stop.

**Installation method**
Official Docker image `jketterl/openwebrx-soapyremote:latest-aarch64` on Arch Linux ARM on Rock64,
SoapyRemote is running at system level, on Arch Linux ARM on a Raspberry Pi 2.

**Versions**
`OpenWebRX version v0.21.0-dev`

**Log messages**
`openwebrx    | WARNING: SoapySDR::Device::readStream timeout!`

**Additional context**
No additional context.

**Comment by jketterl** [comment]
I'm sorry, but this is not an OpenWebRX error. As you can probably tell, a timeout is reported from the SoapySDR API, indicating that something has gone wrong. OpenWebRX has no means of keeping the stream running at this point, nor does it have any information as to what actually happened.

If you believe this timeout is unjustified, you should bring this up with SoapyRemote or SoapySDR.
