### ISSUE TITLE
SDRplay API version 2 reference outdated

### ISSUE THREAD

**Issue by waterwin** [jketterl/openwebrx#221]
For API version 2, please use https://github.com/pothosware/SoapySDRPlay
For API version 3, please use https://github.com/SDRplay/SoapySDRPlay

Both links go to the same page for API version 3 probably because at the SDRplay website I can also only find the API 3 now.

It appears that API 2 is finally laid at rest.

**Comment by jketterl** [comment]
I see... too bad, API version 3 hasn't seen any updates ever since it was still considered beta, and there's a still lot of problems with it...

I will remove Version 2 from the docs. It shouldn't be in use in any of the builds any more. Thanks for the hint.

**Comment by waterwin** [comment]
Building with API 3 now on Dragonboard 410C ARM64.

**Comment by jketterl** [comment]
good luck :slightly_smiling_face: 

wiki page has been updated and version 2 is no longer mentioned.

**Comment by waterwin** [comment]
You ARE fast Sir.
;-)
Erwin
    On Monday, March 1, 2021, 05:38:32 PM GMT+1, Jakob Ketterl <notifications@github.com> wrote:  
 
 


good luck 🙂
 
wiki page has been updated and version 2 is no longer mentioned.
