### ISSUE TITLE
Incorrect range setting.

### ISSUE THREAD

**Issue by IkaSGC** [jketterl/openwebrx#225]
Hi, I'm completely new to this WebSDR. I have the basic settings here "RTL-SDR USB Stick" for 2m and 70cm. 

But my SDR handles 100khz - 1.7 GHz. How can I reset these basic settings? Is the correct configuration file available somewhere? Thank you.

![ScreenHunter_29 Mar  23 14 22](https://user-images.githubusercontent.com/7561343/112155136-4c5f0780-8be5-11eb-87d4-14f006289ea1.jpg)
![ScreenHunter_30 Mar  23 14 22](https://user-images.githubusercontent.com/7561343/112155138-4c5f0780-8be5-11eb-8ddf-f2d47346ee42.jpg)

**Comment by jketterl** [comment]
This is not an OpenWebRX issue. Please use the mailing list for support requests.

**Comment by IkaSGC** [comment]
Where i find that mailing list??

**Comment by jketterl** [comment]
You went right past it: When you click "New issue", there's three options. The third one is the mailing list.

https://groups.io/g/openwebrx
