### ISSUE TITLE
Settings saved in different places

### ISSUE THREAD

**Issue by andlil** [jketterl/openwebrx#231]
**Describe the bug**
settings.json and users.json are stored in /var/lib/openwebrx instead of /etc/openwebrx in Docker image

**To Reproduce**
Make change to profile, remove docker container, start docker container, change is gone...

**Expected behavior**
All settings should be stored in one location /etc/openwebrx

**Installation method**
Docker image

**Versions**
0.21.0-dev a17690d

**Comment by jketterl** [comment]
This is not a bug. The new location has been chosen specifically to conform with the FHS.

Migration documentation is being drafted right now that will contain instructions on how to handle the volumes.
