### ISSUE TITLE
Feature Request: Add an option per profile to exec a bash command line when a profile starts or changes

### ISSUE THREAD

**Issue by hubertmeier** [jketterl/openwebrx#236]
**Feature description**
If a profile is started or changed and there is an option start_command" then the python script makes a system call which is stored in the option and runs this command or the whole command line in a hidden terminal, an output is not needed. This should be not so difficult because your interface has the possibility to add options and python can make the system calls. The option must accept all characters which can be used in bash. A second command for leaving the profile is not necessarily needed, this could be implemented in the logic of the individual external devices. I think, recognizing the leaving of the profile is more difficult.  

The goal is that one has the possibility to start a bash script (php, python) or make HTTP-Requests per wget to other devices to switch antennas, power on power supllies (18V QO100, 12V LNAs, and so on). This would be _ultra flexible_ and would enable to control internal or external devices from all possible systems (RPI4 with its Pins, PC, VMs which has no internal possibilities).

**Target audience**
Any user who wants to control external (Anel Power Switches, ESP8266, Tasmota, Homematic ...) or internal (IO-Pins, i2c per python scripts) devices for switching power supplies, bias tees, antenna, lights, whatever.

**Comment by jketterl** [comment]
This has been requested before, but unfortunately my answer still remains the same: No. Running external commands is completely arbitrary and too error-prone and risky.

See previous discussions:
- https://groups.io/g/openwebrx/topic/78719228#2131
- https://github.com/jketterl/openwebrx/issues/179
- https://github.com/jketterl/openwebrx/issues/110
