### ISSUE TITLE
Setting the lfo_offset for the receiver or for the profiles does not accept negative values

### ISSUE THREAD

**Issue by hubertmeier** [jketterl/openwebrx#247]
**Bug description**
Setting the **lfo_offset** for the receiver or for the profiles does not accept negative values. The field is empty after submitting a negative value

**To Reproduce**
in any form in OWRX 1.0

**Expected behavior**
Most converters converts up, so a positive value is ok, a LNB for QO-100 converts down, so i need a negative lfo_offset

**Installation method**
Raspberry Pi SD card image

**Versions**
1.0

**Log messages**
Are there any relevant messages relating to the bug in the output / log of OpenWebRX? (On most installations, the log should be available using the command `sudo journalctl -u openwebrx`)

**Additional context**

**Comment by jketterl** [comment]
The rendering in the client did indeed not evaluate negative numbers, and while they were saved initially, the inputs vanished on the next save. Should be fixed now.
