### ISSUE TITLE
DMR no audio

### ISSUE THREAD

**Issue by mojso** [jketterl/openwebrx#248]
hello
 
why is there no audio when I try DMR
where I make a mistake with installation

/tmp/openwebrx/openwebrx_pipe_dmr_control_pipe_1973800848
but this folder is empty /tmp/openwebrx in raspbian
 
I use raspberry pi 3b + and raspbian
  openwebrx - docker image

this is the command I am running openwebrx v1.0.0
docker run --device /dev/bus/usb -p 8073:8073 -v openwebrx-settings:/var/lib/openwebrx  --tmpfs=/tmp/openwebrx jketterl/openwebrx:stable

**Comment by jketterl** [comment]
Please use the issue template. Please post support requests on the groups.io mailing list.
