### ISSUE TITLE
Some features: Tetra, dPMR .. .. 

### ISSUE THREAD

**Issue by Klammraute** [jketterl/openwebrx#250]
Hi! Could you please add some of the following features?

Support for Tetra Digital and dPMR
Feature: Waterfall recording/saving for xMhz to xMhz for x time (0,5-24 hours)

Feature for soundactivated recording

Thank you for your work!

73

**Comment by jketterl** [comment]
This is not a place to write personal letters. If you want to see features added, please fill out the corresponding template (once for each feature)!

Also, please take a minute to check existing requests, both tetra and dpmr are already on the list.
