### ISSUE TITLE
Settings page password

### ISSUE THREAD

**Issue by cwmoriarty** [jketterl/openwebrx#252]
What is the default username/password for the `https://<docker>:8073/login?ref=settings` page ?

It's not pi/raspberry

**Comment by jketterl** [comment]
please use the issue template. please use the mailing list for support request. please refer to the wiki for documentation.

**Comment by cwmoriarty** [comment]
Found this in wiki, was a bit buried:

https://github.com/jketterl/openwebrx/wiki/User-Management

**Comment by jketterl** [comment]
It's not buried, it's right there in the sidebar.
