### ISSUE TITLE
How to use Soapy_remote and/or rtl_tcp?

### ISSUE THREAD

**Issue by Niemand112233** [jketterl/openwebrx#255]
Hi,

where can I configure a connection to soapy_remote or rtl_tcp? I can't find anything in the docs.

**Comment by jketterl** [comment]
Please use the groups.io mailing list for support requests. This area is reserved exclusively for issues within the software.

**Comment by Niemand112233** [comment]
This isn't very userfriendly since I don't have an account at groups.io

**Comment by Niemand112233** [comment]
> Please use the groups.io mailing list for support requests. This area is reserved exclusively for issues within the software.

This isn't very userfriendly since I don't have an account at groups.io

**Comment by jketterl** [comment]
You don't need to have an account there. All you need is a valid e-mail address.

It's not very friendly to expect that I shift the way I provide support around just because it doesn't suit you. I don't see why some individuals think the world around needs to change to match their comfort.
