### ISSUE TITLE
FT8 band reported to PSKReporter turns into "Unknown" as soon OpenWebRX switches into background mode

### ISSUE THREAD

**Issue by dm5tt** [jketterl/openwebrx#259]
**Describe the bug**

Band shows up as "Unknown" in PSKReporter when running in background decoding mode.

Everything looks fine when its in the foreground

**To Reproduce**

1. Enable FT8 Background decoding in 2m Band
2. Compare spots in PSKReporter when OpenWebRX is in foreground  or  background mode

**Expected behavior**

Showing "2m" band not not "Unknown"

**Installation method**

Docker

**Versions**

2021-07-18 12:33:22,390 - owrx.__main__ - INFO - OpenWebRX version v1.1.0-dev starting up...

Latest Docker pull from "openwebrx-full."

Ubuntu 21.04, AMD64

**Log messages**

No related error/warnings

**Additional context**

Here you can see the 2m band reported correctly in foreground mode. As soon it switches into the background the band turns into "Unknown"

![image](https://user-images.githubusercontent.com/87605596/126066995-f017d213-6c6b-47f1-956d-20a315306b39.png)

Had a look at all old tickets reported here. This one seems to be new.

**Comment by jketterl** [comment]
The band (as seen in the screenshot) is not reported by OpenWebRX, in fact the pskreporter API does not even have a "band" field. It is determined by pskreporter based on the reported frequency.

**Comment by dm5tt** [comment]
Hmm.. OK. Thank you!

**Comment by dm5tt** [comment]
Band reportings reappeared. Looks like this was a PSKReporter hickup.
