### ISSUE TITLE
Second channel muted, but still sounding

### ISSUE THREAD

**Issue by DE8MSH** [jketterl/openwebrx#26]
Hi Jakob.

If I use DMR and I muted one channel while two stations are talking same time, the muted station is still hearable. 

I know you fixed it. But it still happens.

73 and thx!

**Comment by jketterl** [comment]
did you update digiham recently? i did some work to prevent both channels playing at the same time, so i may have broken something there.

the other occasion i have seen this was when the client auto-reconnects, seems like the frontend and dsp get out of sync.

**Comment by jketterl** [comment]
I am moving this issue over to the digiham project, it is probably an issue in the code there.

**Comment by DE8MSH** [comment]
Hey. After updating digiham like this

https://github.com/jketterl/digiham/commit/d76a73a124619235e079eb261ec5742386b57fc3

it works again.
