### ISSUE TITLE
hpsdrconnector accepts only integer gain values

### ISSUE THREAD

**Issue by rolnas** [jketterl/openwebrx#260]
**Describe the bug**
Tried to use hpsdrconnector to HL2 and it is not working if gain is set via web interface.

**To Reproduce**
Add hpsdr device and set gain via settings web interface.

**Expected behavior**
rf_gain values should be integer (for most cases).

**Installation method**
OpenWebRX was installed manually from official manual.

**Versions**
OpenWebRX version 1.0 (master branch).

**Log messages**
Log had message about invalid gain value supplied (not integer, but for e.g. 18.0)

**Additional context**
No idea how to solve. Probably this value in web interface should remain as written by user and not converted to n.0 format.
Web browsers tried - Firefox and Chrome on Linux.

**Comment by jketterl** [comment]
duplicate, see #256
