### ISSUE TITLE
Digimodes not showing up for decoding

### ISSUE THREAD

**Issue by knoedel001** [jketterl/openwebrx#263]
Hello,

the digimodes (DMR in particular) are not showing up for decoding on the webinterface, the buttons on the control panel are missing. The problem exists on the Raspberry Pi image of August 3rd and on a manual Docker image installation for the pi, as well as in v1.0.0. I tried Firefox and Chromium, both recent version.

What did I miss to get the Digimodes working?

Edit to add: Pi 4 2GB
![grafik](https://user-images.githubusercontent.com/43000162/131009540-2f670988-1935-44e0-b301-3ebab794a1ad.png)

**Comment by petrkr** [comment]
As I had same problem after one two years update.. Maybe whould be nice to mention that on wiki? Like "you need special HW decoder for 100-300USD' I was actually able to find all info after half day googling what AMBE is. But maybe it would much help less experienced peoples if there will be such not.

Also would be nice add supported HW for AMBE dongles. I for now order DVStick3003 as I found in source codes it should be supported.

Regards Petr

**Comment by dc7ds** [comment]
did you see this: https://github.com/jketterl/openwebrx/wiki/AMBE-vocoder-device-notes

**Comment by petrkr** [comment]
Yes, that is already example configuration for some device. But as person, who never heard AMBE you are lost in forest.

I am programmer, IT administrator, so I figured it out. This suggest was just for newbies or someone who is not much experienced in IT, but very experienced in radio.

Maybe if I'll get some time at work, i'll try to do some template of documentation (even it's something what me, like almost all programmers, hate) :)
