### ISSUE TITLE
No Settings Button on openwebrx GUI

### ISSUE THREAD

**Issue by anthropic-radio-source** [jketterl/openwebrx#264]
**Describe the bug**
On my openwebrx gui, there is no Settings button shown. The other buttons (Status, Log, Receiver, Map) show and work OK. This happens wheter I am full screen or reduced screen.

**To Reproduce**
It happens all the time even after a full reboot.

**Expected behavior**
To show the Settings button

**Installation method**
How did you install OpenWebRX?  - Raspberry Pi SD card image, 

**Versions**
What version of OpenWebRX are you running? V1.1.0

**Log message

OpenWebRX client log
Author contact: Jakob Ketterl, DD5JFK | OpenWebRX homepage
Support and information: Groups.io Mailinglist
WebSocket opened to ws://192.168.1.195:8073/ws/
Server acknowledged WebSocket connection.
Audio stream is compressed.
FFT stream is compressed.
Web Audio API succesfully initialized, using ScriptProcessorNode API, sample rate: 48000 Hz

**Additional context**

None.

![openwebrx_no_settings_button](https://user-images.githubusercontent.com/37216683/132226777-30405747-5cf6-4a36-a91f-a6833ad80e1f.jpg)

**Comment by jketterl** [comment]
This doesn't look like version 1.1.0 to me. Versions 1.0 and newer will report their version in the client output log like this:

```
Server acknowledged WebSocket connection, OpenWebRX version: v1.1.0
```

Your log is showing the old message format without the version, indicating version 0.20 or older. Please double-check the version and update as required.

**Comment by anthropic-radio-source** [comment]
Jakob Thanks for getting back so quick. I’ll check again. I was sure it was 1.1.0 but obviously not! Keep up the good work mate. Regards ARS From: Jakob KetterlSent: 06 September 2021 14:57To: jketterl/openwebrxCc: anthropic-radio-source; AuthorSubject: Re: [jketterl/openwebrx] No Settings Button on openwebrx GUI (#264) This doesn't look like version 1.1.0 to me. Versions 1.0 and newer will report their version in the client output log like this:Server acknowledged WebSocket connection, OpenWebRX version: v1.1.0Your log is showing the old message format without the version, indicating version 0.20 or older. Please double-check the version and update as required.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anthropic-radio-source** [comment]
Jakob Doh! I thought I was opening the openwebrx on the RPi 4 image I downloaded from the GitHub site, when in fact I was opening the openwebrx on a RPi 4 running the latest Dragon OS image. The Dragon OS version is obviously not the latest openwebrx. Once again, my apologies for wasting your time. Regards ARS From: Jakob KetterlSent: 06 September 2021 14:57To: jketterl/openwebrxCc: anthropic-radio-source; AuthorSubject: Re: [jketterl/openwebrx] No Settings Button on openwebrx GUI (#264) This doesn't look like version 1.1.0 to me. Versions 1.0 and newer will report their version in the client output log like this:Server acknowledged WebSocket connection, OpenWebRX version: v1.1.0Your log is showing the old message format without the version, indicating version 0.20 or older. Please double-check the version and update as required.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jketterl** [comment]
No problem. I don't know exactly how the installation on DragonOS works or how to update it. If it's using the repository, it should be possible to update using the package manager.
