### ISSUE TITLE
Prometheus metrics break on invalid digital mode names

### ISSUE THREAD

**Issue by doccodyblue** [jketterl/openwebrx#266]
If a band entry in bands.json is used for background decoding and the entry has a -space- in the name 
it leads to a space in the prometheus metric, forcing the prometheus parser to break.

**To Reproduce**
1. in bands.json:
{
    "name": "11m CB",
    "lower_bound": 26965000,
    "upper_bound": 27405000,
    "frequencies": {
      "js8": 27245000
    },
    "tags": ["public"]
  },

2. decode a js8 signal on 11m (or fake it)
3. find the following metrics entry in /metrics:
js8call_decodes_11m CB_JS8_total 4

**Expected behavior**
Spaces in the description of the metric should be replaces by underscores

**Installation method**
from git

**Versions**
1.2.0-dev

**Comment by jketterl** [comment]
Please use the issue template.
@doismellburning: can you confirm this? suggestions on how to mitigate?

**Comment by jketterl** [comment]
If I remember correctly, this was addressed by #273, so can we close this?

**Comment by doccodyblue** [comment]
Yes, thank you, all working!
