### ISSUE TITLE
migrating / import SDR device settings and profiles

### ISSUE THREAD

**Issue by cptechnik** [jketterl/openwebrx#270]
put old files in /home/pi

pi@owrx:~ $ sudo mv *.* /etc/openwebrx
pi@owrx:~ $ sudo service openwebrx stop 
pi@owrx:~ $ sudo openwebrx config migrate
Migrating configuration...
Migrating bookmarks...
Migration complete!
pi@owrx:~ $ sudo service openwebrx start 
pi@owrx:~ $ reboot

... starting browser with webif and config... devices are not converted...

**Comment by jketterl** [comment]
Please use the issue template. Please use the groups.io mailing list for support questions.
