### ISSUE TITLE
Feature request: Add armv6 docker image

### ISSUE THREAD

**Issue by JoostvdB94** [jketterl/openwebrx#278]
Currently there are a few supported processor architectures OpenWebRX provides an image for: 
- armv7
- aarch64
- x86_64

Would it be possible to add a armv6 image to this list? 
armv6 is used in the first RaspberryPi models, and also in the first RaspberryPi Zero models.
I think these tiny machines have enough system resources to run OpenWebRX, because i've run a similar product on them before (ShineySDR). 

I personally think it would be great if we could repurpose these older raspberry pi models to be SDR receivers.

**Comment by jketterl** [comment]
Sorry, but this will probably not happen. Two major reasons:

The Raspberry Pi devices using the armv6 architecture are the original Raspberry Pi 1 and the Raspberry Pi Zero. In my experience, these devices do not have the necessary computing power to run OpenWebRX in a reasonable way. The Raspberry Pi 2 (the first quad-core Pi) is the lowest you can go, and that came with armv7l.

Second, the images are built natively, i.e. on a Raspberry Pi 4. The current build time is somewhere around 4 hours. I really do not want to know how long it would take to build these images on a Pi 1.

If you really wish to run OpenWebRX on an earlier CPU, you can either go with the manual installation procedure, or you can try building the docker images locally using the `docker.sh` in the project root. The builds should be reproducible, but I'm not sure if all the compiler optimization arguments will line up for armv6, so not sure how well this will go.
