### ISSUE TITLE
Build image on the latest Raspbian Bullseye

### ISSUE THREAD

**Issue by edegraaff** [jketterl/openwebrx#285]
Before posting a new feature request, please check if a similar idea has already been listed
* on the issue tracker
* on the [OpenWebRX github project](https://github.com/users/jketterl/projects/1).
Seems my request is not yet on your list.

**Feature description**
This project has served me so well and solved a lot of issues at home as starting radio amateur. 
I have tried to do a full system upgrade to Debian Bullseye, and i solved a lot of issues there but at the end i failed.
The request:
Function export and import your own bookmarks (as part of system livecycle)
New version of OpenWebRX on Bullseye as image 

**Target audience**
Audience all that use OpenWebRX 
And 
Radio Amateurs that want to use GeoIP firewalling on the OpenWebRX image, since in Bullseye the GeoIP filters do work again.

Great Christmas
Eelco

**Comment by jketterl** [comment]
The next release will be on Debian Bullseye. I don't plan to build extra images until then.
