### ISSUE TITLE
MPX Output for WFM

### ISSUE THREAD

**Issue by RaA-BLNET** [jketterl/openwebrx#286]
**Feature description**
MPX Output would be a pretty nice addition to the WFM demodulator. With it, we can handle stereo demodulation / RDS decoding on our end with e.g. MPX Tool or RDS Spy.
The audio bandwidth needs to be >192kHz, otherwise parts of the FM MPX Signal will get cut off.

**Target audience**
Mainly for FM-DX.

**Comment by jketterl** [comment]
The idea of OpenWebRX is to embed the decoders so that everybody can use them through the web interface without having to setup additional decoders on their end. As such, there is no need to send high-bandwidth audio to the client.
