### ISSUE TITLE
Wrong WSPR 80m bookmark frequency

### ISSUE THREAD

**Issue by YO8TNB** [jketterl/openwebrx#288]
**Describe the bug**
On 80m band WSPR bookmark is set on wrong frequency 3.5926 and should be 3.5686.

**To Reproduce**
Go to 80m and click WSPR bookmark.

**Expected behavior**
If we set background decode for WSPR on 80m will be no decode at all if frequency is wrong.

**Installation method**
Raspberry Pi SD card image (latest)

**Versions**
2021-08-03-OpenWebRX-full

**Log messages**
Are there any relevant messages relating to the bug in the output / log of OpenWebRX? (On most installations, the log should be available using the command `sudo journalctl -u openwebrx`)

**Additional context**

**Comment by jketterl** [comment]
This has already been fixed in #281
