### ISSUE TITLE
Cannot access web settings or change frequency range in bans-file

### ISSUE THREAD

**Issue by Magnusmd** [jketterl/openwebrx#290]
Hi, by the life of me I cannot log in to the web-settings area with any standard Pi password. That the SDR-RTL dongle is locked to 2 m and 70 cm band is unneccesary. Please open the SDR-dongle for all frequencies and please provide the password for the web-configuration.

Kind regards

Magnus de LB9YI

**Comment by jketterl** [comment]
Please use the mailing list for support requests. Please check the documentation in the wiki for information on how to set up web configuration access.
