### ISSUE TITLE
Higher waterfall zoom (rather a question, posting it here so others can find it more easily)

### ISSUE THREAD

**Issue by Bosslike65** [jketterl/openwebrx#291]
Is it possible to have a higher quality of zoom in openwebrx? Like if you zoom into 200Khz, it is already pixelated, on the other hand while on KiwiSDR, which is a fork of owrx, you can zoom into about 4Khz and still maintain nice and sharp waterfall.  So the question is, would it be possible to set it to a higher quality? And if not, would it be possible for you to add it?

![obrázok](https://user-images.githubusercontent.com/74657405/155009676-b399e9c8-5744-42b5-8b41-be5bc84b3126.png)
![obrázok](https://user-images.githubusercontent.com/74657405/155010059-66a2cb51-1c0b-48ce-a727-55376d511513.png)

Thanks

**Comment by jketterl** [comment]
Please use the mailing list for questions.
