### ISSUE TITLE
HackRF Amp Settings Not Applied

### ISSUE THREAD

**Issue by ReProgram8a9ce45a** [jketterl/openwebrx#298]
When setting up the HackRF, and turning on the amp via by specifying the gain for each stage in the device settings, the setting is preserved and applied to the HackRF if there is a current session open. However, upon the closing of a the session, and reactivation, the AMP setting is not preserved.

**To Reproduce**
Create a HackRF Device entry
Add the option to specify each gain stage individually
Enter 13 in the Amp box to enable to amp.
Notice the amp setting is applied to a currently open session. However, if all sessions are closed, and one is opened after, the setting is preserved in OpenWebRX but not applied to the HackRF. The other gain settings for the LNA and VGA are applied correctly.

**Expected behavior**
The AMP setting should be applied when OpenWebRX initializes the HackRF..

**Installation method**
Installed on DragonOS using the sources.

**Versions**
Version 1,1

**Additional context**
The HackRF is not a sensitive receiver on VHF without the amp so fixing this would really help.

**Comment by jketterl** [comment]
I can reproduce the problem, but unfortunately I cannot fix this. The connector receives the initial gain setting, and performs the corresponding calls on the SoapySDR API. I have added some debug output into the corresponding methods, the output on initial startup of the device looks like this:

```
2022-05-26 15:14:37,348 - owrx.source - INFO - Started sdr source: soapy_connector -g AMP=13 -s 500000 -f 14150000 -p 51487 -c 56327 -d driver=hackrf
setting up control socket...
control socket started on 56327
socket setup complete, waiting for connections
client connection established
2022-05-26 15:14:37,448 - owrx.source.connector - DEBUG - opening control socket...
control connection established
[ ... client initialization happening here ... ]
2022-05-26 15:14:37,957 - owrx.source - DEBUG - activating profile 20m for hackrf
[INFO] Opening rad1o #0 a83065d9254e0a27...
2022-05-26 15:14:38,642 - owrx.service - DEBUG - re-scheduling services due to sdr changes
2022-05-26 15:14:38,643 - owrx.service - DEBUG - sdr source is unavailable
closing client socket
performing gain change...
 setting multi gain: AMP=13; 
```

The last line originates from a debug output inserted right above [this line](https://github.com/jketterl/owrx_connector/blob/develop/src/app/soapy_connector.cpp#L241). This happens without any edit or change of profile.

It should be investigated by the developers of [SoapyHackRF](https://github.com/pothosware/SoapyHackRF) and / or [libhackrf](https://github.com/greatscottgadgets/hackrf) why the call to `setGain()` has no effect under the given circumstances.
