### ISSUE TITLE
Automatic forwarding after 10-60 seconds of the openwebrx-sdr-profiles-listbox

### ISSUE THREAD

**Issue by Watchkido** [jketterl/openwebrx#301]
Please install a switch with which the openwebrx-sdr-profiles-listbox can be switched automatically every 10-60 seconds.
Target:
- for monitoring large frequency ranges
- for monitoring several ham bands
- Band observation / propagation conditions
- finding local sources of interference
- etc

If you reject this extension, I would be grateful for a hint how I can implement this extension myself.
Batch, Powershell, Browser Plugin, .... [Autohotkey](https://www.autohotkey.com/) is too unreliable

Thanks

**Comment by jketterl** [comment]
I don't see how this would become a feature in OpenWebRX. Switching profiles affects all connected users, so this feature would be in conflict with the multi-user aspect of the software.
