### ISSUE TITLE
Is there a way to move all the docker images to alpine?

### ISSUE THREAD

**Issue by hellmind** [jketterl/openwebrx#302]
Is there a way to move all the docker images to alpine?
Is there a reason for using debian 11 ?

**Comment by jketterl** [comment]
Please use the issue template. Please use the mailing list for questions and support.

Alpine, or more precisely musl, has caused a number of issues with this project in the past, and when it became clear that it does not support FMV, I rebased all docker images on Debian (see https://github.com/jketterl/openwebrx/issues/38). I am very happy that I did and I wouldn't even want to switch back even if that particular problem was resolved by now.
