### ISSUE TITLE
Multiple SDRPlay

### ISSUE THREAD

**Issue by Terminator0007** [jketterl/openwebrx#315]
How to choose one from two SDRPlay devices ? I have RSPduo and RSPdx connected to different antennas but identification with serial number doesn't work. I can't find any information about multiple SDRPlay in Openwebrx. Device identification is possible to choose correct input during settings device but doesn't work. Both SDRPlay device are connected to RaspberryPi to USB. Is this identification function working or is only planned ?

**Comment by jketterl** [comment]
Please use the groups.io mailing list for support questions.
