### ISSUE TITLE
Can't add RTL-SDR serial numbers with new UI 

### ISSUE THREAD

**Issue by dcmk1mr2** [jketterl/openwebrx#319]
**Describe the bug**

Can't run multiple RTL-SDRs as there is no place to assign serial numbers to the device.

**To Reproduce**
Steps to reproduce the behavior.

I tried "device":"serial=00001001" for soapy, and "device":"00001001" with non-soapy in the Device Name field.  

Only one RTL-SDR runs, other are shown as unknown.

**Expected behavior**

A three RTL-SDR runs receivers

**Installation method**
How did you install OpenWebRX? (Raspberry Pi SD card image, Debian / Ubuntu packages, Docker image, manually?)

Raspi SD Card Image

**Versions**
What version of OpenWebRX are you running? (Check on startup, or see `owrx/version.py`. If a `-dev` version is used, ideally state the commit the issue is appearing on)

v1.2.0

**Log messages**
Are there any relevant messages relating to the bug in the output / log of OpenWebRX? (On most installations, the log should be available using the command `sudo journalctl -u openwebrx`)

**Additional context**

**Comment by jketterl** [comment]
Please use the [groups.io mailing list](https://groups.io/g/openwebrx) for support requests.
