### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by itan2105** [jketterl/openwebrx#321]
Hello everyone! I can't log in via SSH to create a new user in order to change the parameters via the web. Help please. 73!

**Comment by jketterl** [comment]
Please use the groups.io mailing list for support.

Please refer to Rasperry Pi OS resources on how to establish an SSH connection.

**Comment by itan2105** [comment]
when creating an image on the flash, I changed the security settings. everything is working now. Thanks!
