### ISSUE TITLE
On map, hyperlinked callsigns from APRS result in error

### ISSUE THREAD

**Issue by ofadam** [jketterl/openwebrx#322]
**Describe the bug**
Clicking on hyperlinked callsigns on map from APRS decodes results in error from qrzcq.com

**To Reproduce**
Click on hyperlinked callsign.

**Expected behavior**
In order to surface details about a user behind the callsign, strip the APRS SSID before generating the qrzcq.com URL

**Installation method**
Installed from unstable Ubuntu packages

**Versions**
Using development branch, commit 8a7e91be3841f7ac7ac3a462ad8986026100388b

**Log messages**
None relevant.

**Comment by ofadam** [comment]
Updated.

**Comment by jketterl** [comment]
Thank you. Tagging @luarvique since this was one of his additions.

**Comment by luarvique** [comment]
Please, see this pull request:

https://github.com/jketterl/openwebrx/pull/318

It strips the station ID from APRS callsigns, as well as computing and displaying the distance between clicked beacons/squares and the QTH.

**Comment by jketterl** [comment]
Well hidden.

I'm currently looking at the APRS decoder, and it seems like the information is actually separate in the AX25 header, but is merged into a single string right in the beginning. It may be more difficult, but I believe that processing the data correctly may be the better way to go. Let's see...

**Comment by ofadam** [comment]
It looks great now and no longer causes errors when doing a callsign lookup.

**Comment by jketterl** [comment]
Yes, I'm aware. This actually goes deeper, it is part of the AX.25 protocol, which is the base of packet radio in general.

The header format reserves 6 bytes for the callsign itself in ASCII, while the SSID is stored as a 4-bit integer in the 7th byte of the address fields. These two things need to be parsed separately anyway, so carrying this information in a structured way and rendering it at a later point would be my preferred way of solving this.

**Comment by jketterl** [comment]
A late update on this: I changed the internal data model to separate callsigns and SSIDs and updated the rendering now. I didn't see any new issues popping up, so I'll close this as resolved for now. If there is still problems, please don't hesitate to open a new issue.
