### ISSUE TITLE
Python error in log file, just forwarding information, not blocking

### ISSUE THREAD

**Issue by yah00078** [jketterl/openwebrx#325]
Hello, 
During normal function, i can see python error in log file, I only forward the information, it don't generate any issues, i'am on python 3.9.2

Have a nice day! 

Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: 2022-10-17 13:34:54,546 - owrx.websocket - ERROR - ValueError while writing data
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: Traceback (most recent call last):
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]:   File "/usr/lib/python3/dist-packages/owrx/websocket.py", line 146, in _sendBytes
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]:     (_, write, _) = select.select([], [self.handler.wfile], [], 10)
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: ValueError: file descriptor cannot be a negative integer (-1)
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: 2022-10-17 13:34:54,547 - owrx.websocket - WARNING - _sendBytes() after socket error, ignoring
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: 2022-10-17 13:34:54,570 - owrx.websocket - ERROR - ValueError while writing data
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: Traceback (most recent call last):
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]:   File "/usr/lib/python3/dist-packages/owrx/websocket.py", line 146, in _sendBytes
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]:     (_, write, _) = select.select([], [self.handler.wfile], [], 10)
Oct 17 13:34:54 NSY-PI-RADIO openwebrx[31376]: ValueError: file descriptor cannot be a negative integer (-1)

**Comment by jketterl** [comment]
Please use the issue template!

Is there any information on how to reproduce the error? Any previous errors in the logs?

The `self.handler.wfile` that is causing the error is part of the native python webserver, so if that variable becomes -1 without triggering any of the installed error handling cases, there's very little that OpenWebRX can do. It could of course check for that specific condition, but I'd say that's unreasonable unless the error is sufficiently understood.
