### ISSUE TITLE
rtl_sdr device not detected

### ISSUE THREAD

**Issue by wri3ght** [jketterl/openwebrx#328]
**Describe the bug**
I installed OWRX yesterday, and the device was shown in the journalctl log.
Nov 04 19:20:15 Pi64 openwebrx[10771]:   0:  Realtek, RTL2838UHIDIR, SN: 00000006
In the web interface, the tuner/receiver seemed be working.
Today, it is not shown in the startup long and of course the web receiver is not working.

**To Reproduce**
I have restarted the Pi, and replugged the tuner.
No change.

**Expected behavior**
The device is listed by lsusb...
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I expected to see the device shown above in the journalctl log.

**Installation method**
This is on a Raspberry Pi 4.
I followed the Debian package install.

**Versions**
1.2.1 

**Log messages**
The device is not listed AND I get this...
owrx.connection - WARNING - no more SDR devices available

**Additional context**
I did check that the "blacklist" rule was in /etc/modprobe.d/blacklist_rtl2832
blacklist dvb_usb_rtl28xxu
blacklist rtl2832
blacklist rtl2830
blacklist rtl2838

gqrx and op25 work just fine.

**Comment by jketterl** [comment]
Please use the mailing list for support requests.

If the device is no longer listed, OpenWebRX cannot use it. Please check your hardware and contact your device vendor if necessary.
