### ISSUE TITLE
No Digital Decode

### ISSUE THREAD

**Issue by dellacer1** [jketterl/openwebrx#33]
Hello my Name is Andy,

I don´t have the Digimods on the Website, can you help me what is wrong?
The add-ons are installed.
![Bildschirmfoto zu 2019-12-10 22-24-32](https://user-images.githubusercontent.com/58751372/70570381-1175c380-1b9c-11ea-9026-077b80dfd00d.png)

Andy

**Comment by jketterl** [comment]
Hello Andy,

the most common cause of this is a missing dependency, most likely the `sox` application (I have missed that myself many times). You can easily check what's missing, just append `/features` to your receiver URL (e.g. http://openwebrx/features). That will bring up a feature report, which will show you what specific dependencies are missing.

**Comment by dellacer1** [comment]
Thanks,
It works good.
Andy
