### ISSUE TITLE
Implement variable POCSAG 512/1200/2400 Decoding

### ISSUE THREAD

**Issue by LiamDroog** [jketterl/openwebrx#332]
**Feature description**
Add the ability to switch between POCSAG 512/1200/2400 under the POCSAG digital mode. Or, implement the ability to automatically detect and decode POCSAG baud rate. I have tested the current POCSAG decoder and it fails to decode 512 messages that multimon-ng can catch.

**Target audience**
Anyone who lives near a metro area interested in listening in on the POCSAG-ness of the city

**Comment by jketterl** [comment]
This has been discussed before, see:

https://groups.io/g/openwebrx/topic/77190400
https://groups.io/g/openwebrx/topic/74837069

Currently blocked by UI constraints.
