### ISSUE TITLE
No boot partition with image 2022-09-30-OpenWebRX-full.img?

### ISSUE THREAD

**Issue by oe8bck** [jketterl/openwebrx#334]
I copied 2022-09-30-OpenWebRX-full.img  to a SD-card, but the boot partition is empty. (I used dd on my Linux box)

```
$ lsblk /dev/sdc
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdc      8:32   1 14,5G  0 disk 
├─sdc1   8:33   1  256M  0 part 
└─sdc2   8:34   1  2,1G  0 part /media/user/rootfs
```
I can mount ```/dev/sdc1```but it's empty, the  files mentioned in https://www.raspberrypi.com/documentation/computers/configuration.html#the-boot-folder are missing.
```
/dev/sdc1 on /media/user/WEBRX type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
```

Maybe someone can give me a hint what I did wrong.

73 de OE8BCK Christof

**Comment by jketterl** [comment]
Please use the issue template.
Please use the [groups.io mailing](https://groups.io/g/openwebrx) list for support requests.
