### ISSUE TITLE
Audio becomes garbled after some time on iOS Safari

### ISSUE THREAD

**Issue by codyc1515** [jketterl/openwebrx#336]
**Describe the bug**
After a short period of time, audio becomes garbled when listening in iOS Safari web browser. Refreshing the page helps for a short period of time, then it becomes garbled once more necessitating further refreshes.

**To Reproduce**
Listen on an iOS device using Safari for 30-60 seconds and observe that the audio becomes garbled.

**Expected behavior**
No, or minimal, interruptions in audio.

**Installation method**
Docker image on Raspberry Pi 4 (4GB RAM)

**Versions**
Latest jketterl/openwebrx:stable

**Log messages**
I cannot observe anything.

**Additional context**
Despite the issues on iOS Safari, it works okay on macOS Safari.

**Comment by jketterl** [comment]
As previously discussed in #303, neither iOS nor Safari are currently supported.

See also https://github.com/jketterl/openwebrx/wiki/Client-Support
