### ISSUE TITLE
Overflow error on uploading to pskreporter at 10GHz band

### ISSUE THREAD

**Issue by takgr** [jketterl/openwebrx#338]
While decoding FT8 on QO-100 at 10489.400 Mhz an error appears:

File "/opt/openwebrx/owrx/reporting/pskreporter.py", line 145, in encodeSpot
    + list(int(spot["freq"]).to_bytes(4, "big"))
OverflowError: int too big to convert

Version is the latest on dockerhub (v1.2.0-dev)

**Comment by jketterl** [comment]
Please use the issue template!

Indeed, but that's a limitation of the [pskreporter protocol](https://pskreporter.info/pskdev.html): It only reserves 4 bytes for the frequency. That allows a maximum frequency of ~4.3GHZ.
