### ISSUE TITLE
Overflow error on uploading to pskreporter at 10GHz band [correct template]

### ISSUE THREAD

**Issue by takgr** [jketterl/openwebrx#339]
While decoding FT8 on QO-100 at 10489.540 Mhz the spot cannot be uploaded to pskreporter

**To Reproduce**
A receiver should tune to QO-100 downlink frequency at 10489.540 MHz

**Expected behavior**
The current FT8 frequency should be correctly reported to pskreporter.info

**Installation method**
Docker

**Versions**
Version is the latest on dockerhub (v1.2.0-dev)

**Log messages**
File "/opt/openwebrx/owrx/reporting/pskreporter.py", line 145, in encodeSpot
+ list(int(spot["freq"]).to_bytes(4, "big"))
OverflowError: int too big to convert

**Additional context**
Latest version of WSJT-X software correctly uploads spots to server using the specified API
A partial wireshark dump of the packet sent by WSJT-X follows:

Flow 3
    Enterprise Private entry: (Philip Gladstone) Type 1: Value (hex bytes): 45 41 32 41 41
    Enterprise Private entry: (Philip Gladstone) Type 5: Value (hex bytes): 02 71 39 b7 35
    Enterprise Private entry: (Philip Gladstone) Type 6: Value (hex bytes): 04
    Enterprise Private entry: (Philip Gladstone) Type 10: Value (hex bytes): 46 54 38
    Enterprise Private entry: (Philip Gladstone) Type 3: Value (hex bytes): 49 4e 38 33
    Enterprise Private entry: (Philip Gladstone) Type 11: Value (hex bytes): 01
    StartTime: Feb 20, 2023 15:52:11.000000000 EET

Type 5 refers to frequency, which if converted from hex to dec results in: 10489542453 Hz

**Comment by jketterl** [comment]
As I already explained yesterday, this is a limitation in the pskreporter reporting API. The frequency is explicitly specified as a 4-byte integer. 2^32 = 4294967296 - anything higher than that cannot be reported with the currently specified protocol.

If you feel like this is a problem, you should get in touch with the devs at pskreporter and have them implement a protocol that allows for more bytes.

**Comment by jketterl** [comment]
https://twitter.com/dd5jfk/status/1627677102269992964

**Comment by jketterl** [comment]
https://twitter.com/n1dq/status/1627848208192794627

See, that wasn't that hard, was it?

**Comment by jketterl** [comment]
Should be fixed in `develop`. Please test.

**Comment by takgr** [comment]
Tested and working!
