### ISSUE TITLE
New AM Profile Issue

### ISSUE THREAD

**Issue by larryiweaver** [jketterl/openwebrx#340]
I am a new user. I created a new profile for the AM Broadcast band in the US with an AirspyHF+ Discovery. I used the same settings that are used in the 49 Meter profile that came already configured, other than the frequencies. When I select the new profile OpenWebRX starts up with broken audio and a very fast waterfall and then crashes. I need to reboot my Raspberry Pi to connect to OpenWebRX again.
     I am using a Raspberry Pi 4 with 2GB of RAM and the Pi image. OpenWebRX shows version 1.2.1

Thank you,
Larry

**Comment by jketterl** [comment]
Please use the issue template.
Please use the [groups.io mailing list](https://groups.io/g/openwebrx) for support.
