### ISSUE TITLE
No audio dmr in rpi3

### ISSUE THREAD

**Issue by beppelpo** [jketterl/openwebrx#347]
In my Rpi 3, with 2022-09-30-OpenWebRX-ful.img installed I can't demodulate the signals in DMR, with chrome I listen only to the classic noise in fm, if I switch to DMR mode absolute silence both with RTL-SDR stick than with Rsp1. All the other ways work well indeed very well!

**Comment by petrkr** [comment]
And which decoder for AMBE you are using?

https://github.com/jketterl/openwebrx/wiki/AMBE-vocoder-device-notes

I have DVStick33 and it works fine

**Comment by jketterl** [comment]
Please use the issue template.
Please use the groups.io mailing list for support.
Also, please check the FAQ about decoding AMBE modes.
