### ISSUE TITLE
APRS: Some symbols point EAST, others point NORTH (or nowhere)

### ISSUE THREAD

**Issue by luarvique** [jketterl/openwebrx#352]
**Describe the bug**
Current code assumes all APRS symbols pointing EAST, making NORTH-pointing symbols point in the wrong direction.

**To Reproduce**
Just find an airplane.

**Expected behavior**
North-heading airplane should point north.

**Installation method**
Packages

**Versions**
OWRX 1.2.1 and derived (OWRX+)

**Log messages**
Nope

**Additional context**
See proposed solution in the following message.

**Comment by luarvique** [comment]
Here is the proposed solution, which essentially filters out east-pointing symbols for the special rotation algorithm:

```
    const FACING_EAST = "(*<=>CFPUXYabefghjkpsuv[";

    if (!this.course) {
        div.style.transform = null;
    } else if (this.symbol && !FACING_EAST.includes(this.symbol.symbol)) {
        // Airplanes and other symbols point up (to the north)
        div.style.transform = 'rotate(' + this.course + 'deg)';
    } else if (this.course > 180) {
        // Vehicles and vessels point right (to the east)
        div.style.transform = 'scalex(-1) rotate(' + (270 - this.course) + 'deg)'
    } else {
        // Vehicles and vessels point right (to the east)
        div.style.transform = 'rotate(' + (this.course - 90) + 'deg)';
    }
```

**Comment by jketterl** [comment]
Thanks. I worked this out a bit more to also include the symbol table, see commit above.

**Comment by luarvique** [comment]
Acknowledged. I skipped on the table selection, since most of the alt table symbols looked ok rotating either way. But this look more complete.
