### ISSUE TITLE
Shown center frequency setting

### ISSUE THREAD

**Issue by JJi-588** [jketterl/openwebrx#353]
Hello everyone,
I have AirSpy R2 and Spyverter R2 upconverter in use.
Back in the day, there was a "shown_center_freq"-setting in config_webrx.py that one can use to control what frequency is shown in the UI, while using an upconverter.

As the frequency shift in the upconverter is 120MHz, the value needs to be reduced somehow so I can use it properly with bookmarks and bands. I tried adding the line "shown_center_freq", in openwebrx.conf to the profile in question, but that had no effect.

If this particular feature is not yet implemented, I would love to see that in the future, if possible.

**Comment by jketterl** [comment]
Please use the issue template.
Please use the mailing list for support requests.
