### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by elmogosogo09usa** [jketterl/openwebrx#356]
**Feature description**
Hi i am elliot and i want openwebrx to be supported on windows it's because what if they don't have linux installed and they wnat to install open web rx instead they can be supported for windows.

**Target audience**
Everyone

**Comment by jketterl** [comment]
Not going to happen unless you're willing to maintain it yourself.

There's no big hurdles in installing Linux either. It's even free. If you don't have Linux this is solely due to your own choices.
