### ISSUE TITLE
First client in control

### ISSUE THREAD

**Issue by horga83** [jketterl/openwebrx#360]
Description:

For SDR's with only one receiver.
First client to connect has control, all other clients are essentially "read only".  Admin user has control no matter what and can boot all other clients.

**Comment by jketterl** [comment]
This has been discussed before, and it's a pretty distinct "no". One of the principles of OpenWebRX is that clients are treated fair, and get the same level of control as all the others. This means that there will be no preference of one connection over the other, completely independent of whether one of them was first, or one of them is "admin".
