### ISSUE TITLE
Add Certbot ability to your embedded web server

### ISSUE THREAD

**Issue by scannerbrightly** [jketterl/openwebrx#362]
**Feature description**
Please add Certbot to the default Rasp Pi image and the ability to use the certificate generated to have a free, correct SSL certificate for any install that might see the public internet. Certbot is a free snap that will work with the already installed nginx server. [This forum post ](https://groups.io/g/openwebrx/topic/102136322#8874) gets me part of the way, and seems to be the only suggested way of getting a Let's Encrypt cert installed.

If you try to install certbot on your own, it fails when trying to contact https://[domain name]/.well-known/acme-challenge/[key here], as OpenWebRX is replying 404. 

**Target audience**
Any OpenWebRX user who wants to put their install on the public internet.

**Comment by jketterl** [comment]
Sorry, but that is really a task for the operator / admin of the receiver, and is not a job that OpenWebRX will take on for you.
