### ISSUE TITLE
SoapyRemote seems to not function

### ISSUE THREAD

**Issue by idarlund** [jketterl/openwebrx#372]
**Describe the bug**
"Device connected to a SoapyRemote server" seems to not function. When opening openwebrx I'm getting "No SDR Devices available". Also I don't see any outbound network traffic going to the configured IP:PORT.

**To Reproduce**
1. Add "Device connected to a SoapyRemote server".
2. Enter all details like this:
![Screenshot from 2024-02-06 15-16-27](https://github.com/jketterl/openwebrx/assets/3417634/4db63952-7b2f-49de-af22-cab830420279)
3. Open web-interface

**Expected behavior**
Working device

**Installation method**
Either preinstalled or apt install in DragonOS

**Versions**
v1.2.1

**Log messages**
2024-02-06 15:17:40,246 - owrx.connection - WARNING - no more SDR devices available

**Additional context**
When checking with SoapySDRUtil I do find the device:

```
$ SoapySDRUtil --find="remote=10.5.31.38, remote:driver=rtlsdr, serial=00001620"
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

[WARNING] SoapyVOLKConverters: no VOLK config file found. Run volk_profile for best performance.
[INFO] [UHD] linux; GNU C++ version 11.3.0; Boost_107400; UHD_4.1.0.5-0-unknown
Found device 0
  available = Yes
  driver = remote
  label = Generic RTL2832U OEM :: 00001620
  manufacturer = Nooelec
  product = NESDR SMArt v5
  remote = tcp://10.5.31.38:55132
  remote:driver = rtlsdr
  rtl = 0
  serial = 00001620
  tuner = Rafael Micro R820T
```

When checking traffic with tcpdump on the openwebrx machine, I see the outgoing (and incoming) traffic when running SoapySDRUtil, but I see nothing when adding the device in openwebrx or open webgui in openwebrx.

**Comment by jketterl** [comment]
Please use the [groups.io mailing list](https://groups.io/g/openwebrx) for support.

Sceenshot and lack of error messages show that you don't have a profile set up. Profiles are required for devices to function.
