### ISSUE TITLE
Feature Request: 5 decimals (10 Hz) resolution on frequency

### ISSUE THREAD

**Issue by ktuulos** [jketterl/openwebrx#388]
**Feature description**
Currently OpenWebRX frequency setting has 4 decimals, meaning it has 100 Hz resolution. This makes it non-optimal for e.g. PMR446 monitoring, as its channels have separation by 5 decimals, 10 Hz: PMR1 = 446.00625 MHz, PMR2 = 446.01875 MHz etc.

It is known that most SDR receivers can't have this much accuracy, but this would anyway make the display consistent with actual channel frequencies.

**Target audience**
PMR446 listeners

**Comment by jketterl** [comment]
This is adjustable. Check the "Tuning precision" under "General settings" in the web configuration.
