### ISSUE TITLE
Nan Hz

### ISSUE THREAD

**Issue by aa5af5607** [jketterl/openwebrx#392]
The openwebrx won't let me enter a frequency it tells me NaN Hz how do you correct that
Robby

**Comment by jketterl** [comment]
Please use the issue template.
Please use the [groups.io mailing list](https://groups.io/g/openwebrx) for support requests.

**Comment by aa5af5607** [comment]
Didn't get any help from nobody on the group Sent from my iPhoneOn Nov 13, 2024, at 9:46 AM, Jakob Ketterl ***@***.***> wrote:﻿
Please use the issue template.
Please use the groups.io mailing list for support requests.

**Comment by jketterl** [comment]
That doesn't mean you can bring your issues here. Also, I don't remember seeing any topics that would relate to your message there.

**Comment by aa5af5607** [comment]
Maybe because I'm a newbie and it hasn't been released by the moderator yet Sent from my iPhoneOn Nov 13, 2024, at 10:48 AM, Jakob Ketterl ***@***.***> wrote:﻿
That doesn't mean you can bring your issues here. Also, I don't remember seeing any topics that would relate to your message there.

**Comment by jketterl** [comment]
You do realize I can see when you signed up and sent your messages there? I can clearly tell that you sent your messages after you claimed that you "Didn't get any help from nobody on the group".

Please stop shitting on our community if you haven't even bothered.
