### ISSUE TITLE
Install openwebrx by setup.py - openwebrx.conf location

### ISSUE THREAD

**Issue by D3vil0p3r** [jketterl/openwebrx#393]
**Describe the bug**
I installed openwebrx by setup.py correctly.

I read the docs but the process by `setup.py` does not create `openwebrx.conf` file automatically. Should I create it manually? If so, in which location should I place it?

**Comment by jketterl** [comment]
Please use the issue template.
Please use the[ groups.io mailing list](https://groups.io/g/openwebrx) for support.

None of the documented installation procedures involves invoking `setup.py`. That file mostly exists for the Debian packaging process. It doesn't really cover the full installation by any means, and you'll probably have to handle a lot of stuff manually.

I recommend you read the [manual installation instructions](https://github.com/jketterl/openwebrx/wiki/Manual-Package-installation-(including-digital-voice)) on the wiki.
