### ISSUE TITLE
Fax Reception failed (v1.2.74)

### ISSUE THREAD

**Issue by df6dbf** [jketterl/openwebrx#397]
In the latest Release the receive from Fax Transmissions from (DWD Pinneberg or GYA Northwood) its not possible to get an Image.
It seems that the start of the Picture is recognized.

![Bild_2024-12-15_225502351](https://github.com/user-attachments/assets/88b083cf-ef68-4319-bc97-aa87555672ee)

Kind regards, Holger

**Comment by jketterl** [comment]
Please use the issue template.

Version 1.2.74 is not an official version of OpenWebRX. The latest stable version of OpenWebRX is 1.2.2, which does not have a FAX decoder. Neither does the experimental version.

Please report your issues to the respective fork maintainers.
