### ISSUE TITLE
airspy with bias-tee ?

### ISSUE THREAD

**Issue by nmaster2042** [jketterl/openwebrx#40]
Is there a config file option that enable bias-tee on airspy ?

I need this to power the spyverter upconverter.

**Comment by jketterl** [comment]
there is :slightly_smiling_face: check the config example here: https://github.com/jketterl/openwebrx/wiki/Sample-Configuration-for-Airspy-R2---Mini

there's two lines that need to be enabled by removing the "#" in front of them:

```
        "bias_tee": True,
        "lfo_offset": 120000000,
```

**Comment by jketterl** [comment]
sorry, hit the wrong button. will wait for your feedback before i close :)

**Comment by nmaster2042** [comment]
Sorry, I didn't pay attention there was wiki pages.

All is fine. Thank you very much.
