### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by sm4xas** [jketterl/openwebrx#45]
Just cloned the rep, as I did a few days ago on a Pi.
git clone https://github.com/jketterl/openwebrx/

Got this error:

OpenWebRX - Open Source SDR Web App for Everyone!  | for license see LICENSE file in the package
_________________________________________________________________________________________________

Author contact info:    Jakob Ketterl, DD5JFK <dd5jfk@darc.de>

Traceback (most recent call last):
  File "./openwebrx.py", line 6, in <module>
    main()
  File "/home/pi/openwebrx/owrx/__main__.py", line 33, in main
    pm = PropertyManager.getSharedInstance().loadConfig()
  File "/home/pi/openwebrx/owrx/config.py", line 140, in loadConfig
    cfg = importlib.util.module_from_spec(spec)
AttributeError: 'module' object has no attribute 'module_from_spec'

Any ideas?
Docker version works however I cannot get the rtl_sdr_soapy to work so I would like to be able to run /features to see if it detecs it. SoapyRTLSDR installed and working.

**Comment by jketterl** [comment]
could be the python version. what are you using? minimum is 3.5 right now.

**Comment by jketterl** [comment]
the docker version doesn't include the rtl_sdr soapy driver. i can include it in the next build, if that helps.

**Comment by sm4xas** [comment]
Please do. I'll try it on my other Pi3, right now I'm testing on my Pi2 and it's probably too old dist. The latest python in the reps is 3.4.2.

**Comment by jketterl** [comment]
alright, the builds just went through, docker images should now include the soapy module. the config still needs to be edited though.

**Comment by jketterl** [comment]
closing this since `rtl_sdr_soapy` and `direct_sampling` are reported working in multiple cases.
