### ISSUE TITLE
RasPi - No module named 'pkg_resources' -- solved

### ISSUE THREAD

**Issue by Sinager** [jketterl/openwebrx#57]
Just in case someone else stumbles in the issue, as I did

sudo apt-get install python3-pkg-resources

Raspbian uses Python2 as a default, so Python3 and the abpve package must be installed.

Thanks for the good work.

**Comment by jketterl** [comment]
Just out of curiosity: in what context did you need it? It should be installed automatically with the packages. Did you try to use the setup.py for a local install?
