### ISSUE TITLE
NFM doesn`t work

### ISSUE THREAD

**Issue by UB0ALH** [jketterl/openwebrx#74]
Perfect work! Excellent indeed!
I hear FM in AM in big nose. I clearly hear DMR. But in FM I hear only sizzle (((
Few hours ago all was perfect.  
I edited /etc/openwebrx/config_webrx.py  - maybe I did something wrong in it?

**Comment by jketterl** [comment]
Did you use a different device when listening a few hours ago? I am suspecting you may have an unsupported version of csdr installed.

**Comment by UB0ALH** [comment]
No. I can`t do this - I have only one RTL-SDR (RTL2838).

**Comment by jketterl** [comment]
Sorry I should have been more specific. I was referring to "device" as in client, so did you use a different browser, computer, smartphone or tablet?

**Comment by UB0ALH** [comment]
))) I`m stupid fool!!! In Chrome it works 59 )))

I used Firefox before. Cleaning cache didn`t help - that should I do?

**Comment by jketterl** [comment]
Try to install csdr from here: https://github.com/jketterl/csdr

your description of the problem plus the fact that you probably had an install of an older version of OpenWebRX on this machine means you're probably using an older version of csdr right now. While that is _mostly_ ok, it lacks the NFM deemphasis filter for 12kHz.

**Comment by UB0ALH** [comment]
Ok. Thank  you very match !
