### ISSUE TITLE
Path to JS

### ISSUE THREAD

**Issue by UB0ALH** [jketterl/openwebrx#75]
index.html:
"...
       <script src="static/openwebrx.js"></script>
        <script src="static/lib/jquery-3.2.1.min.js"></script>
        <script src="static/lib/jquery.nanoscroller.js"></script>
        <script src="static/lib/BookmarkBar.js"></script>
        <script src="static/lib/AudioEngine.js"></script>
        <script src="static/lib/ProgressBar.js"></script>
        <script src="static/lib/Measurement.js"></script>
        <script src="static/lib/FrequencyDisplay.js"></script>
        <link rel="stylesheet" type="text/css" href="static/lib/nanoscroller.css" />
        <link rel="stylesheet" type="text/css" href="static/css/openwebrx.css" />
..."

But in folder there is folder "static". All files are in "lib" folder. If I change "static/lib" on "lib" it doesn`t work at all. How it works?!

**Comment by jketterl** [comment]
Well since this is an issue, the main thing is that it does work... So, does it work?

OpenWebRX isn't a regular webserver. It serves static files through the `/static` prefix. What comes after that (i.e. `lib/jquery-3.2.1.min.js`) relates to the "htdocs" folder in the checkout.

**Comment by UB0ALH** [comment]
Thanks! I`ll search information for this item!
