### ISSUE TITLE
Python 3.X? Support

### ISSUE THREAD

**Issue by linuxonlinehelp** [jketterl/openwebrx#80]
Which Python is supported higher than 2.7? Found no Requirements Details on this fork sites.

**Comment by jketterl** [comment]
python 2.7 is no longer supported. minimum requirement right now is python 3.5.

**Comment by jketterl** [comment]
Requirement has been added for the manual installation documentation: https://github.com/jketterl/openwebrx/wiki/Manual-Package-installation-(including-digital-voice)

Docker and Rasperry Pi images come with the necessary version pre-installed, and the packages are using the package manager to ensure that requirements are met, so there's no need to document it for those.
