### ISSUE TITLE
Question Public SDR List on https://www.openwebrx.de?

### ISSUE THREAD

**Issue by linuxonlinehelp** [jketterl/openwebrx#85]
purged

**Comment by amontefusco** [comment]
I agree. 
Ad besides, who is maintaining that site now?

**Comment by jketterl** [comment]
I agree with you, and I don't really understand the reasoning of the callsign requirement. But, building a new index is quite a bit of work, and I haven't gotten round to it yet. There's a lot of work on OpenWebRX itself as it is right now :wink: 

Also, I do have a few ideas on how to improve things. Mostly, I'd like to build an open index, i.e. not limited to OpenWebRX, so it'll probably not be on openwebrx.de.

**Comment by amontefusco** [comment]
> I agree with you, and I don't really understand the reason for the callsign requirement.

Maybe because it guarantees the uniqueness of the primary key :-)

**Comment by linuxonlinehelp** [comment]
purged
