### ISSUE TITLE
Negative network usage

### ISSUE THREAD

**Issue by D0han** [jketterl/openwebrx#88]
Because I had some connection issues websocket was closed and reconnected. This resulted in showing negative network usage.  
![image](https://user-images.githubusercontent.com/2964404/76839302-90326a80-6835-11ea-8378-aeb2e36e7833.png)

**Comment by jketterl** [comment]
Looks like the timers didn't get reset properly when the connection restarted. Need to look into this, but shouldn't be that hard to fix.

**Comment by jketterl** [comment]
It's an issue with the averaging algorithm that makes the values less "jumpy". The network usage was affected since the averaging is done over 60s, so it was visible for quite some time. Fix coming up in a minute
