### ISSUE TITLE
squelch_level

### ISSUE THREAD

**Issue by UB0ALH** [jketterl/openwebrx#91]
Can I set up the default squelch_level in start up?

**Comment by jketterl** [comment]
Yes you can :) All you need to set is the `initial_squelch_level`. Should work per device and per profile, but as always: if you want to use it on a profile, all profiles will need to have that setting.

BTW, I think it's time you head over to our mailing list https://groups.io/g/openwebrx - much better place to ask questions. Issues should be things that don't work as intended :)

**Comment by UB0ALH** [comment]
sorry! ok )))
i should mail to openwebrx@groups.io ?

**Comment by jketterl** [comment]
I think you'll have to subscribe before any messages are accepted via E-Mail. I'm using the website for all my posting, so I'm not too familiar with the mailing stuff.

**Comment by jketterl** [comment]
Btw: if you happen to have discord, you can also join us there :) https://discord.gg/SxwEhke

**Comment by jketterl** [comment]
is this issue still ongoing, or can we close it up? just asking because there's never been any feeback if the `initial_squelch_level` works :wink:
