### ISSUE TITLE
Multiple SDR Dongles on a single Raspy

### ISSUE THREAD

**Issue by cybernano96** [jketterl/openwebrx#93]
Hello, i have multiple SDR Keys and i want to use them with different softwares, how can i set the "-d 1" attribute in rtl_tcp, i can't find the string that start the receiver

**Comment by jketterl** [comment]
The command is built dynamically, and it doesn't use `rtl_tcp` anymore. You can still configure an identifier on sdr by using the `device` key:

```
sdrs = {
    "rtlsdr": {
        "name": "RTL-SDR USB Stick",
        "type": "rtl_sdr",
        "ppm": 0,
        "device": "1",
        [... other device properties ...]
        "profiles": {
            [...]
```

**Comment by cybernano96** [comment]
Thanks, I'll try

**Comment by cybernano96** [comment]
it works!

**Comment by jketterl** [comment]
awesome! :)

**Comment by v01t** [comment]
@jketterl how to specify remote endpoint address for rtl_tcp like 172.16.25.1:1234?
Thanks.

**Comment by jketterl** [comment]
Commenting on closed, unrelated issues is the best way to never get an answer. Please use the mailing list for questions, issues are for bugs.

`rtl_tcp` is not a supported source, you can only use a locally installed stick as a source right now.
